const Placedstudentsdetails2 = [
    { id: 1, name: "Dinesh Kore", role: "Software Test Enginner", photo: "./img/placed students/s1.png" },
    { id: 2, name: "Amit Kale", role: "Python Automation Test Engineer", photo: "./img/placed students/s2.png" },
    { id: 3, name: "Minu Jadhav", role: "Flutter Developer", photo: "./img/placed students/s3.png" },
    { id: 4, name: "Devshree", role: "Flutter Developer;", photo: "./img/placed students/s4.png" },
    { id: 5, name: "Gautame Gaikwad", role: "Python Developer", photo: "./img/placed students/s5.png" },
    { id: 6, name: "Madhavi Chavan", role: "Python Automation Test Enginner", photo: "./img/placed students/s6.png" },
    { id: 7, name: "Shaikh Lal", role: "Admin Support", photo: "./img/placed students/s7.png" },
    { id: 8, name: "", role: "", photo: "./img/placed students/s8.png" },
    { id: 9, name: "", role: "", photo: "./img/placed students/s9.png" },
    { id: 10, name: "", role: "", photo: "./img/placed students/s10.png" },
    { id: 11, name: "", role: "", photo: "./img/placed students/s11.png" },
    { id: 12, name: "", role: "", photo: "./img/placed students/s12.png" },
    { id: 13, name: "", role: "", photo: "./img/placed students/s13.png" },
    { id: 14, name: "", role: "", photo: "./img/placed students/s14.png" },
    { id: 15, name: "", role: "", photo: "./img/placed students/s15.png" },
    { id: 16, name: "", role: "", photo: "./img/placed students/s16.png" },
    { id: 17, name: "", role: "", photo: "./img/placed students/s17.png" },
    { id: 18, name: "", role: "", photo: "./img/placed students/s18.png" },
    { id: 19, name: "", role: "", photo: "./img/placed students/s19.png" },
    { id: 20, name: "", role: "", photo: "./img/placed students/s20.png" },
    { id: 21, name: "", role: "", photo: "./img/placed students/s21.png" },
    { id: 22, name: "", role: "", photo: "./img/placed students/s22.png" },
    { id: 23, name: "", role: "", photo: "./img/placed students/s23.png" },
    { id: 24, name: "", role: "", photo: "./img/placed students/s24.png" },
    { id: 25, name: "", role: "", photo: "./img/placed students/s25.png" }
]
export default Placedstudentsdetails2;