import React from 'react'
import { Container, Row, Col} from 'react-bootstrap'
import Footer from "./footer"

const Privatepolicy = () => {
    return (
        <section className=''>
            <div className='py-5 bg-light' >
                <Row className='d-flex justify-content-evenly align-items-center container'>
                    <Col><h1 className='text-center  fw-bold  py-5'>Privacy Policy</h1></Col>
                    <Col><img src="./img/policy/private1.png" alt="" width={300} height={200} /></Col>
                </Row>
            </div>
        <div >
            <Container>
                <Row className='py-5 text-light'>

                    <p>Our Privacy Policy was last updated on [1 st Jan 2023].</p>
                    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                    <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy was generated by TermsFeed Privacy Policy Generator.</p>
                    <h2>Interpretation and Definitions</h2>
                    <h3>Interpretation</h3>
                    <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                    <h2>Definitions</h2>
                    <p>For the purposes of these Terms and Conditions:</p>
                    <Container>
                        <ul>
                            <li style={{ "list-style-type": "square" }}>Account means a unique account created for You to access our Service or parts of our Service.</li>
                            <li style={{ "list-style-type": "square" }}>Business, for the purpose of the CCPA (California Consumer Privacy Act), refers to the Company as the legal entity that collects Consumers, personal information and determines the purposes and means of the processing of Consumers, personal information, or on behalf of which such information is collected and that alone, or jointly with others, determines the purposes and means of the processing of consumers, personal information, that does business in the State of California.</li>
                            <li style={{ "list-style-type": "square" }}>Company (referred to as either the Company,We,Us or Our in this Agreement) refers to [Bright InfoTech] For the purpose of the GDPR, the Company is the Data Controller.</li>
                            <li style={{ "list-style-type": "square" }}>Country refers to [INDIA].</li>
                            <li style={{ "list-style-type": "square" }}>Consumer, for the purpose of the CCPA (California Consumer Privacy Act), means a natural person who is a California resident. A resident, as defined in the law, includes (1) every individual who is in the USA for other than a temporary or transitory purpose, and (2) every individual who is domiciled in the USA who is outside the USA for a temporary or transitory purpose.</li>
                            <li style={{ "list-style-type": "square" }}>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                            </li>
                            <li style={{ "list-style-type": "square" }}>Device means any device that can access the Service such as a computer, a cell phone or a digital tablet.
                            </li>
                            <li style={{ "list-style-type": "square" }}>Do Not Track (DNT) is a concept that has been promoted by US regulatory authorities, in particular the U.S. Federal Trade Commission (FTC), for the Internet industry to develop and implement a mechanism for allowing internet users to control the tracking of their online activities across websites.</li>
                            <li style={{ "list-style-type": "square" }}>Personal Data is any information that relates to an identified or identifiable individual. For the purposes of GDPR, Personal Data means any information relating to You such as a name, an identification number, location data, online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity. For the purposes of the CCPA, Personal Data means any information that identifies, relates to, describes or is capable of being associated with, or could reasonably be linked, directly or indirectly, with You.</li>
                            <li style={{ "list-style-type": "square" }}>Sale, for the purpose of the CCPA (California Consumer Privacy Act), means selling, renting, releasing, disclosing, disseminating, making available, transferring, or otherwise communicating orally, in writing, or by electronic or other means, a Consumerâ€™s personal information to another business or a third party for monetary or other valuable consideration.</li>
                            <li style={{ "list-style-type": "square" }}>Service refers to the Website.</li>
                            <li style={{ "list-style-type": "square" }}>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. For the purpose of the GDPR, Service Providers are considered Data Processors.</li>
                            <li style={{ "list-style-type": "square" }}>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                            <li style={{ "list-style-type": "square" }}>Website refers to [BrightInfoTech], accessible from [https://brightinfo.in/]</li>
                            <li style={{ "list-style-type": "square" }}>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. Under GDPR (General Data Protection Regulation), You can be referred to as the Data Subject or as the User as you are the individual using the Service.</li>
                        </ul>
                    </Container>
                    <h2>Collecting and Using Your Personal Data</h2>
                    <h3>Types of Data Collected</h3>
                    <p>Personal Data</p>
                    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                    <ul>
                        <li style={{ "list-style-type": "square" }}>Email address</li>
                        <li style={{ "list-style-type": "square" }}>First name and last name</li>
                        <li style={{ "list-style-type": "square" }}>Phone number</li>
                        <li style={{ "list-style-type": "square" }}>Address, State, Province, ZIP/Postal code, City
                        </li>
                        <li style={{ "list-style-type": "square" }}>Usage Data</li>

                    </ul>
                    <p>Usage Data</p>
                    <p>Usage Data is collected automatically when using the Service</p>
                    <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                    <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                    <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
                    <p>Tracking Technologies and Cookies</p>
                    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                    <ul>
                        <li style={{ "list-style-type": "square" }}>Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                        <li style={{ "list-style-type": "square" }}>Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>

                    </ul>
                    <p>Cookies can be Persistent or Session Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
                    <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
                    <ul>
                        <li style={{ "list-style-type": "square" }}>Necessary / Essential Cookies
                        </li>
                        <li>Type: Session Cookies</li>
                        <li> Administered by: Us </li>
                        <p> Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                        <li></li>
                    </ul>

                    <ul>
                        <li style={{ "list-style-type": "square" }}>Cookies Policy / Notice Acceptance Cookies
                        </li>
                        <li>Type: Persistent Cookies</li>
                        <li>Administered by: Us</li>
                        <li>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
                    </ul>


                    <ul>
                        <li style={{ "list-style-type": "square" }}>Functionality Cookies
                        </li>
                        <li>Type: Persistent Cookies</li>
                        <li>Administered by: Us</li>
                        <li>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
                    </ul>

                    <ul>
                        <li style={{ "list-style-type": "square" }}>Tracking and Performance Cookies</li>
                        <li>Type: Persistent Cookies</li>
                        <li>Administered by: Third-Parties</li>
                        <li>Administered by: Third-Parties
                            Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our users react to them.</li>
                        <li>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</li>
                    </ul>
                    <h1 className="text-center">Collecting and Using Your Personal Data</h1>
                    <h2>Types of Data Collected</h2>
                    <p>Personal Data</p>
                    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                    <p>* Email address</p>
                    <p>* First name and last name</p>
                    <p>* Phone number</p>
                    <p>* Address, State, Province, ZIP/Postal code, City</p>
                    <p>* Usage Data</p>

                    <p>Usage Data</p>
                    <p>Usage Data is collected automatically when using the Service.</p>
                    <p>Usage Data may include information such as Your Deviceâ€™s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                    <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                    <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
                    <p>Tracking Technologies and Cookies</p>
                    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                    <p><b>* Cookies or Browser Cookies.</b>A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</p>
                    <p><b>* Web Beacons.</b>Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</p>
                    <p>Cookies can be â€œPersistentâ€ or â€œSessionâ€ Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
                    <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
                    <h2>* Necessary / Essential Cookies</h2>
                    <p>Type: Session Cookies

                    </p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                    <h2>* Cookies Policy / Notice Acceptance Cookies</h2>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                    <h2>* Functionality Cookies</h2>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us

                    </p>
                    <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
                    <h2>* Tracking and Performance Cookies</h2>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Third-Parties</p>
                    <p>Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our users react to them.</p>
                    <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

                </Row>
            </Container>
            </div>
            <Footer/>
        </section>
    )
}

export default Privatepolicy
