import React from 'react'
import { Col, Container, Row } from 'react-bootstrap'
import Footer from "./footer"

const Termsandpolices = () => {
  return (
  
    <section className='container-fluid'>
      <div className='' >  
        <Row className='d-flex justify-content-evenly align-items-center bg-light'>
          <Col><h1 className='text-center  fw-bold  py-5'>Terms and Conditions</h1></Col>
          <Col><img src="./img/policy/terms.png" alt="" width={300} /></Col>
        </Row></div>
     

      
    
        <Row className='px-5 py-4 text-light'>
            <h2>Terms:</h2>
            <p>Our Terms and Conditions were last updated on [1st Jan 2023].</p>
            <p>Please read these terms and conditions carefully before using Our Service.</p>
            <h2>Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            <h2>Definitions</h2>
            <p>For the purposes of these Terms and Conditions:</p>
            <Container>
            <ul>
                <li style={{"list-style-type": "square"}}>Affiliate” means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li style={{"list-style-type": "square"}}>“Account” means a unique account created for You to access our Service or parts of our Service.
                </li>
                <li style={{"list-style-type": "square"}}>“Country” refers to [INDIA].</li>
                <li style={{"list-style-type": "square"}}>“Content” refers to content such as text, images, or other information that can be posted, uploaded, linked to or otherwise made available by You, regardless of the form of that content.</li>
                <li style={{"list-style-type": "square"}}>“Device” means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li style={{"list-style-type": "square"}}>“Feedback” means feedback, innovations or suggestions sent by You regarding the attributes, performance or features of our Service.</li>
                <li style={{"list-style-type": "square"}}>Products” refer to the products or items offered for sale on the Service.
                </li>
                <li style={{"list-style-type": "square"}}>“Orders” mean a request by You to purchase Products from Us.</li>
                <li style={{"list-style-type": "square"}}>“Promotions” refer to contests, sweepstakes or other promotions offered through the Service.</li>
                <li style={{"list-style-type": "square"}}>“Service” refers to the Website.</li>
                <li style={{"list-style-type": "square"}}>“Terms and Conditions” (also referred as “Terms“) mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service. This Terms and Conditions Agreement was generated by TermsFeed Terms and Conditions Generator.</li>
                <li style={{"list-style-type": "square"}}>“Third-party Social Media Service” means any services or content (including data, information, products or services) provided by a third-party that may be displayed, included or made available by the Service.</li>
                <li style={{"list-style-type": "square"}}>“Website” refers to Bright Infotech, accessible from https://brightinfo.in/ You” means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
            </Container>
            <h2>Acknowledgment</h2>
            <p>These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.</p>
            <p>Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.</p>
            <p>By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service.</p>
            <p>You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.</p>
            <p>Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service.</p>
        </Row>
        <Footer/>
        </section>
       
  
  )
}

export default Termsandpolices
